# from django.urls import path
# from rest_framework.routers import DefaultRouter
# from core.views import RecipeViewSet

# # Create a router and register our viewsets with it.
# router = DefaultRouter()
# router.register(r'recipes', RecipeViewSet)

# urlpatterns = [
#     # path('dummy/', views.dummy_view, name='dummy'),
#     # /recipes/<recipe_id>/ingredients/
#     path('recipes/<int:pk>/ingredients/', RecipeViewSet.as_view({'get': 'ingredients'}), name='recipe-ingredients'),
# ]

# # Add the URLs generated by the router to the urlpatterns
# urlpatterns += router.urls


from django.urls import path, include
from rest_framework.routers import DefaultRouter

from core.views import CategoryViewSet, RecipeViewSet # Import both ViewSets

router = DefaultRouter()
router.register(r'recipes', RecipeViewSet, basename='recipe')
router.register(r'categories', CategoryViewSet, basename='category')  # Register CategoryViewSet

urlpatterns = [
    path('', include(router.urls)),  # Include all generated URLs
]